"""add cascade delete for session votes

Revision ID: 119a64d00552
Revises: 629d23245c09
Create Date: 2025-10-13 19:47:05.429281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '119a64d00552'
down_revision: Union[str, Sequence[str], None] = '629d23245c09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pairs', 'prompt_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pairs', 'prompt_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
