"""add_updated_at_to_votes

Revision ID: 6d4b15117fda
Revises: abae5aa694da
Create Date: 2025-11-11 17:41:27.565725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d4b15117fda'
down_revision: Union[str, Sequence[str], None] = 'abae5aa694da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('votes', 'updated_at')
    # ### end Alembic commands ###
