"""add_chunk_system_for_voting

Revision ID: cb080fa92615
Revises: 5c6c0112a5bc
Create Date: 2025-10-18 19:24:43.673799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb080fa92615'
down_revision: Union[str, Sequence[str], None] = '5c6c0112a5bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chunk_pairs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('pair_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pair_id'], ['pairs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id', 'pair_id', name='uq_chunk_pairs_chunk_pair')
    )
    op.add_column('sessions', sa.Column('chunk_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'sessions', 'chunks', ['chunk_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'chunk_id')
    op.drop_table('chunk_pairs')
    op.drop_table('chunks')
    # ### end Alembic commands ###
