"""Add flux and kolors models

Revision ID: dbd30e4a87bf
Revises: cb080fa92615
Create Date: 2025-11-04 22:19:29.358394

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dbd30e4a87bf"
down_revision: Union[str, Sequence[str], None] = "cb080fa92615"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE modelname ADD VALUE IF NOT EXISTS 'flux1_dev'")
    op.execute("ALTER TYPE modelname ADD VALUE IF NOT EXISTS 'flux1_krea'")
    op.execute("ALTER TYPE modelname ADD VALUE IF NOT EXISTS 'kolors'")

    op.execute("ALTER TYPE winner ADD VALUE IF NOT EXISTS 'flux1_dev'")
    op.execute("ALTER TYPE winner ADD VALUE IF NOT EXISTS 'flux1_krea'")
    op.execute("ALTER TYPE winner ADD VALUE IF NOT EXISTS 'kolors'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
